Add jsonnetfmt check into pipeline. (#228)
HO-CTO/sre-monitoring-as-code pull request #234
Opened 2022-09-16 15:19 UTC by mahrufiqbalHO

* Add jsonnetfmt check into pipeline.

* Use the go-jsonnet version of jsonnetfmt and jsonnet.

* Fix issue with path

Co-authored-by: Samiwel Thomas <samiwel.thomas@digital.homeoffice.gov.uk>

2022-09-22 18:07 UTC, michaelpearsonHO approved these changes

2022-09-23 07:56 UTC, michaelpearsonHO requested changes
Appears to need rebasing after other PRs merged.

2022-09-23 07:58 UTC, arifulhaqueHO approved these changes
Fixed merge conflicts. Looks good to me!

2022-09-23 08:13 UTC, arifulhaqueHO commented
Formatted. All checks pass!

2022-09-23 08:21 UTC, michaelpearsonHO approved these changes

2022-09-23 08:21 UTC, merged