244 summary view redesign fired alerts
HO-CTO/sre-monitoring-as-code pull request #245
Opened 2022-09-22 14:12 UTC by georgeowusuHO

2022-09-22 14:23 UTC, mahrufiqbalHO approved these changes

2022-09-22 14:32 UTC, georgeowusuHO commented
This PR is resolves Issue https://github.com/HO-CTO/sre-monitoring-as-code/issues/215 and Jira https://collaboration.homeoffice.gov.uk/jira/browse/L2T-700

2022-09-23 09:40 UTC, michaelpearsonHO requested changes
Over 30 Days should follow style guide of (30d)

2022-09-23 10:36 UTC, michaelpearsonHO approved these changes

2022-09-23 10:37 UTC, merged